version: 1.2
workflows:
   - name: copy_bucket_data_across_regions
     subclass: WDL
     primaryDescriptorPath: /pipelines/migrate_bucket_regions/copy_bucket_data_across_regions.wdl
     testParameterFiles:
     -  empty.json
   - name: migrate_bucket_data_via_local
     subclass: WDL
     primaryDescriptorPath: /pipelines/migrate_bucket_regions/migrate_bucket_data_via_local.wdl
     testParameterFiles:
     -  empty.json
  