version: 1.2
workflows:
 - name: migrate_bucket_data_via_local
   subclass: WDL
   primaryDescriptorPath: /pipelines/migrate_bucket_regions/migrate_bucket_data_via_local.wdl
   testParameterFiles:
    - empty.json

