version: 1.2
workflows:
 - name: migrate_bucket_data_via_local
   subclass: WDL
   primaryDescriptorPath: /pipelines/migrate_bucket_regions/migrate_bucket_data_via_local.wdl
   testParameterFiles:
    - /pipelines/migrate_bucket_regions/empty.json

 - name: create_object_md5
   subclass: WDL
   primaryDescriptorPath: /pipelines/create_object_md5.wdl
   testParameterFiles:
    - /pipelines/empty.json

 - name: deliver_prs_to_anvil
   subclass: WDL
   primaryDescriptorPath: /pipelines/emerge/deliver_prs_to_anvil.wdl
   testParameterFiles:
    - /pipelines/emerge/empty.json

 - name: run_shell_script
   subclass: WDL
   primaryDescriptorPath: /pipelines/run_shell_script.wdl
   testParameterFiles:
    - /pipelines/empty.json

 - name: reheader_cram
   subclass: WDL
   primaryDescriptorPath: /scripts/reheader/reheader_cram.wdl
   testParameterFiles:
    - /scripts/reheader/empty.json

 - name: create_fofn
   subclass: WDL
   primaryDescriptorPath: /pipelines/stanley_center/CreateFoFn.wdl
   testParameterFiles:
    - /pipelines/stanley_center/empty.json