version: 1.2
workflows:
 - name: migrate_bucket_data_via_local
   subclass: WDL
   primaryDescriptorPath: /pipelines/migrate_bucket_regions/migrate_bucket_data_via_local.wdl
   testParameterFiles:
    - empty.json

 - name: create_object_md5
   subclass: WDL
   primaryDescriptorPath: /pipelines/migrate_bucket_regions/create_object_md5.wdl
   testParameterFiles:
    - empty.json

 - name: deliver_prs_to_anvil
   subclass: WDL
   primaryDescriptorPath: /pipelines/emerge/deliver_prs_to_anvil.wdl
   testParameterFiles:
    - empty.json
