version: 1.2
workflows:
 - name: migrate_bucket_data_via_local
   subclass: WDL
   primaryDescriptorPath: /pipelines/migrate_bucket_regions/migrate_bucket_data_via_local.wdl
   testParameterFiles:
    - /pipelines/migrate_bucket_regions/migrate_bucket_data_via_local.wdl

 - name: create_object_md5
   subclass: WDL
   primaryDescriptorPath: /pipelines/create_object_md5.wdl
   testParameterFiles:
    - /pipelines/create_object_md5.wdl

 - name: deliver_prs_to_anvil
   subclass: WDL
   primaryDescriptorPath: /pipelines/emerge/deliver_prs_to_anvil.wdl
   testParameterFiles:
    - /pipelines/emerge/deliver_prs_to_anvil.wdl

 - name: run_shell_script
   subclass: WDL
   primaryDescriptorPath: /pipelines/run_shell_script.wdl
   testParameterFiles:
    - /pipelines/run_shell_script.wdl

 - name: reheader_cram
   subclass: WDL
   primaryDescriptorPath: /scripts/reheader/reheader_cram.wdl
   testParameterFiles:
    - /scripts/reheader/reheader_cram.wdl

 - name: start_dragen
   subclass: WDL
   primaryDescriptorPath: /pipelines/start_dragen/start.wdl
   testParameterFiles:
    - /pipelines/start_dragen/start.wdl

 - name: create_md5
   subclass: WDL
   primaryDescriptorPath: /scripts/create_md5/create_md5.wdl
   testParameterFiles:
    - /scripts/create_md5/create_md5.wdl
