version: 1.2
workflows:
 - name: migrate_bucket_data_via_local
   subclass: WDL
   primaryDescriptorPath: /pipelines/migrate_bucket_regions/migrate_bucket_data_via_local.wdl
   testParameterFiles:
    - empty.json

 - name: create_object_md5
   subclass: WDL
   primaryDescriptorPath: /pipelines/create_object_md5.wdl
   testParameterFiles:
    - empty.json

 - name: deliver_prs_to_anvil
   subclass: WDL
   primaryDescriptorPath: /pipelines/emerge/deliver_prs_to_anvil.wdl
   testParameterFiles:
    - empty.json

 - name: run_shell_script
   subclass: WDL
   primaryDescriptorPath: /pipelines/run_shell_script.wdl
   testParameterFiles:
    - empty.json

 - name: samtools_split
   subclass: WDL
   primaryDescriptorPath: /pipelines/samtools/samtools_split.wdl
   testParameterFiles:
    - empty.json