---
WORKSPACE_NAMESPACE: morgan-fieldeng
WORKSPACE_NAME: launch-workflow-test
METHOD_NAMESPACE: morgan-fieldeng
METHOD_NAME: hello-world-plus-prefixes
SECRET_PATH: projects/<project number>/secrets/<secret name>/versions/1
TRIGGER_PARAMETER_NAME: MyWorkflowName.aCloudStorageFilePath
